apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  displayName: redhat-operators
  image: registry.mydomain.example.com:5000/olm-index/redhat-operator-index:v4.9
  publisher: Red Hat
  sourceType: grpc
