ocp_infra_configs:
  num_masters: 3
  bmc_ip:
    - 10.1.1.10
    - 10.1.1.11
    - 10.1.1.12
  bmc_user: root
  bmc_password: calvin
  bmc_system_path: "/redfish/v1/Systems/System.Embedded.1"
  bmc_insertmedia_path: "/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.InsertMedia"
  bmc_ejectmedia_path: "/redfish/v1/Managers/iDRAC.Embedded.1/VirtualMedia/CD/Actions/VirtualMedia.EjectMedia"
  bmc_resetsystem_path: "/redfish/v1/Systems/System.Embedded.1/Actions/ComputerSystem.Reset"
  http_path: "/usr/share/nginx/html"
cluster_configs:
  name: cu-compact-1
  kind: Cluster
  high_availability_mode: Full
  openshift_version: "4.9"
  ocp_release_image: registry.mydomain.example.com:5000/ocp4:4.9-x86_64
  base_dns_domain: mydomain.example.com
  cluster_networks:
  - cidr: 10.128.0.0/14
    host_prefix: 23
  service_networks:
  - cidr: 172.30.0.0/16
  machine_networks:
  - cidr: 192.168.1.0/25
  pull_secret: "{\"auths\":{\"cloud.openshift.com\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"quay.io\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"registry.connect.redhat.com\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"registry.redhat.io\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"registry.mydomain.example.com:5000\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"test@example.com\"}}}"
  ssh_public_key: "<YOUR_SSH_RSA_KEY>"
  vip_dhcp_allocation: false
  user_managed_networking: false
  platform:
    type: baremetal
  ingress_vip: 192.168.1.61
  api_vip: 192.168.1.60
  additional_ntp_source: 192.168.1.20
  hyperthreading: all
  network_type: OVNKubernetes
  schedulable_masters: true
  cpu_architecture: x86_64
infraenv_configs:
  kind: Infraenv
  name: cu-compact-1-infraenv
  additional_ntp_sources: 192.168.1.20
  ssh_authorized_key: "<YOUR_SSH_RSA_KEY>"
  pull_secret: "{\"auths\":{\"cloud.openshift.com\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"quay.io\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"registry.connect.redhat.com\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"registry.redhat.io\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"youremail@yourdomain.com\"},\"registry.mydomain.example.com:5000\":{\"auth\":\"Zm9vOmJhcg==\",\"email\":\"test@example.com\"}}}"
  ignition_config_override: "{\"ignition\": {\"version\": \"3.1.0\"}, \"storage\": {\"files\": [{\"filesystem\": \"root\",\"overwrite\": true,\"path\": \"/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt\", \"contents\": {\"source\": \"data:text/plain;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCjxZT1VSX1JFR0lTVFJZX0NFUlQ+Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K\"},\"mode\": 420},{\"filesystem\": \"root\",\"overwrite\": true,\"path\": \"/etc/containers/registries.conf\", \"contents\": {\"source\": \"data:text/plain;base64,dW5xdWFsaWZpZWQtc2VhcmNoLXJlZ2lzdHJpZXMgPSBbInJlZ2lzdHJ5LmFjY2Vzcy5yZWRoYXQuY29tIiwgImRvY2tlci5pbyJdCnNob3J0LW5hbWUtbW9kZSA9ICIiCgpbW3JlZ2lzdHJ5XV0KICBwcmVmaXggPSAiIgogIGxvY2F0aW9uID0gInF1YXkuaW8vb3BlbnNoaWZ0LXJlbGVhc2UtZGV2L29jcC12NC4wLWFydC1kZXYiCiAgbWlycm9yLWJ5LWRpZ2VzdC1vbmx5ID0gdHJ1ZQoKICBbW3JlZ2lzdHJ5Lm1pcnJvcl1dCiAgICBsb2NhdGlvbiA9ICJyZWdpc3RyeS5teWRvbWFpbi5leGFtcGxlLmNvbTo1MDAwL29jcDQiCgpbW3JlZ2lzdHJ5XV0KICBwcmVmaXggPSAiIgogIGxvY2F0aW9uID0gInJlZ2lzdHJ5LnJlZGhhdC5pbyIKICBtaXJyb3ItYnktZGlnZXN0LW9ubHkgPSB0cnVlCgogIFtbcmVnaXN0cnkubWlycm9yXV0KICAgIGxvY2F0aW9uID0gInJlZ2lzdHJ5Lm15ZG9tYWluLmV4YW1wbGUuY29tOjUwMDAiCgpbW3JlZ2lzdHJ5XV0KICBwcmVmaXggPSAiIgogIGxvY2F0aW9uID0gInJlZ2lzdHJ5LnJlZGhhdC5pby9yaGFjbTIiCiAgbWlycm9yLWJ5LWRpZ2VzdC1vbmx5ID0gdHJ1ZQoKICBbW3JlZ2lzdHJ5Lm1pcnJvcl1dCiAgICBsb2NhdGlvbiA9ICJyZWdpc3RyeS5teWRvbWFpbi5leGFtcGxlLmNvbTo1MDAwL3JoYWNtMiIK\"},\"mode\": 644}]}}"
  static_network_config:
    - network_yaml: "dns-resolver:\n  config:\n    server:\n      - 192.168.1.20\ninterfaces:\n  - name: eno8303\n    type: ethernet\n    state: down\n  - name: eno8403\n    type: ethernet\n    state: down\n  - name: bond0\n    state: up\n    type: bond\n    mac-address: \"AA:BB:CC:DD:EE:D1\"\n    link-aggregation:\n      mode: 802.3ad\n      options:\n        miimon: \"140\"\n      port:\n        - eno12399\n        - eno12409\n  - name: bond0.11\n    type: vlan\n    vlan:\n      base-iface: bond0\n      id: 11\n    state: up\n    ipv4:\n      enabled: true\n      dhcp: false\n      address:\n        - ip: 192.168.1.51\n          prefix-length: 25\n    ipv6:\n      enabled: false\n  - name: bond0.111\n    type: vlan\n    vlan:\n      base-iface: bond0\n      id: 111\n    state: up\n    ipv4:\n      enabled: true\n      address:\n        - ip: 10.1.111.51\n          prefix-length: 24\n      dhcp: false\n    ipv6:\n      enabled: false\nroutes:\n  config:\n    - destination: 0.0.0.0/0\n      next-hop-address: 192.168.1.1\n      next-hop-interface: bond0.11\n      table_id: 254\n"
      mac_interface_map:
        - mac_address: "AA:BB:CC:DD:EE:D1"
          logical_nic_name: eno12399
        - mac_address: "AA:BB:CC:DD:EE:D2"
          logical_nic_name: eno12409
    - network_yaml: "dns-resolver:\n  config:\n    server:\n      - 192.168.1.20\ninterfaces:\n  - name: eno8303\n    type: ethernet\n    state: down\n  - name: eno8403\n    type: ethernet\n    state: down\n  - name: bond0\n    state: up\n    type: bond\n    mac-address: \"AA:BB:CC:DD:EE:E1\"\n    link-aggregation:\n      mode: 802.3ad\n      options:\n        miimon: \"140\"\n      port:\n        - eno12399\n        - eno12409\n  - name: bond0.11\n    type: vlan\n    vlan:\n      base-iface: bond0\n      id: 11\n    state: up\n    ipv4:\n      enabled: true\n      dhcp: false\n      address:\n        - ip: 192.168.1.52\n          prefix-length: 25\n    ipv6:\n      enabled: false\n  - name: bond0.111\n    type: vlan\n    vlan:\n      base-iface: bond0\n      id: 111\n    state: up\n    ipv4:\n      enabled: true\n      address:\n        - ip: 10.1.111.52\n          prefix-length: 24\n      dhcp: false\n    ipv6:\n      enabled: false\nroutes:\n  config:\n    - destination: 0.0.0.0/0\n      next-hop-address: 192.168.1.1\n      next-hop-interface: bond0.11\n      table_id: 254\n"
      mac_interface_map:
        - mac_address: "AA:BB:CC:DD:EE:E1"
          logical_nic_name: eno12399
        - mac_address: "AA:BB:CC:DD:EE:E2"
          logical_nic_name: eno12409
    - network_yaml: "dns-resolver:\n  config:\n    server:\n      - 192.168.1.20\ninterfaces:\n  - name: eno8303\n    type: ethernet\n    state: down\n  - name: eno8403\n    type: ethernet\n    state: down\n  - name: bond0\n    state: up\n    type: bond\n    mac-address: \"AA:BB:CC:DD:EE:F1\"\n    link-aggregation:\n      mode: 802.3ad\n      options:\n        miimon: \"140\"\n      port:\n        - eno12399\n        - eno12409\n  - name: bond0.11\n    type: vlan\n    vlan:\n      base-iface: bond0\n      id: 11\n    state: up\n    ipv4:\n      enabled: true\n      dhcp: false\n      address:\n        - ip: 192.168.1.53\n          prefix-length: 25\n    ipv6:\n      enabled: false\n  - name: bond0.111\n    type: vlan\n    vlan:\n      base-iface: bond0\n      id: 111\n    state: up\n    ipv4:\n      enabled: true\n      address:\n        - ip: 10.1.111.53\n          prefix-length: 24\n      dhcp: false\n    ipv6:\n      enabled: false\nroutes:\n  config:\n    - destination: 0.0.0.0/0\n      next-hop-address: 192.168.1.1\n      next-hop-interface: bond0.11\n      table_id: 254\n"
      mac_interface_map:
        - mac_address: "AA:BB:CC:DD:EE:F1"
          logical_nic_name: eno12399
        - mac_address: "AA:BB:CC:DD:EE:F2"
          logical_nic_name: eno12409
  image_type: full-iso
  openshift_version: "4.9"
  cpu_architecture: x86_64
